config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do

  get '/auto_complete/projects', controller: 'start', action: 'auto_complete_for_project_name'

  get 'projects/membershiprequest/:id', controller: 'projects', action: 'membershiprequest', as: :requestmembership
  post 'projects/membershiprequest/:id', controller: 'projects', action: 'membershiprequest', as: :request_membership

  match 'roles/workflow/:id/:role_id/:tracker_id', :controller => 'roles', :action => 'workflow', via: :all

  match 'help/:ctrl/:page', :controller => 'help', action: 'index', via: :all

  get 'time_entries/report', :controller => 'time_entry_reports', :action => 'report'
  get 'projects/:project_id/time_entries/report.:format', :controller => 'time_entry_reports', :action => 'report'

  match 'services/projects', :controller => 'project_services', :action => 'index', via: :all
  match 'services/projects/:id', :controller => 'project_services', :action => 'show', via: :all, as: :project_service_show

  match 'services/users/active', :controller => 'user_services', :action => 'active', via: :all
  match 'projects/show/:id', to: redirect('projects/%{id}'), via: :all
  resources :projects do
    get 'wiki.:format', controller: 'wiki', action: 'show'
    put 'wiki_styles/:id.css', controller: 'wiki_styles', action: 'update'
    put 'wiki.css', controller: 'wiki_styles', action: 'update'

  end
end

app/views/projects/_form.html.erb
<%= error_messages_for 'project' %>

<div class="box tabular">
<!--[form:project]-->
<p><%= f.text_field :name, :required => true, :size => 60 %></p>

<p><%= f.text_area :description, :rows => 8, :class => 'wiki-edit' %></p>
<p><%= f.text_field :identifier, :required => true, :size => 60, :disabled => @project.identifier_frozen?, :maxlength => Project::IDENTIFIER_MAX_LENGTH %>
<% unless @project.identifier_frozen? %>
  <em class="info"><%= l(:text_length_between, :min => 1, :max => Project::IDENTIFIER_MAX_LENGTH) %> <%= l(:text_project_identifier_info).html_safe %></em>
<% end %></p>
<p><%= f.text_field :homepage, :size => 60 %></p>
<p><%= f.text_area :quicklinks, :rows => 5 %></p>
<p><%= f.file_field :topbarheaderimage %></p>
<p><%= f.text_field :topbarbackgroundcolor, :rows => 5 %></p>
<p><%= f.text_field :topbartextcolor, :rows => 5 %></p>

<p><%= f.check_box :is_public %></p>

<% unless @project.allowed_parents.compact.empty? %>
  <% if User.current.admin? or User.current.project_move_permission? %>
    <p><%= label(:project, :parent_id, l(:field_parent)) %><%= parent_project_select_tag(@project) %></p>
    <p><%= f.text_field :sorting, :size => 40 %></p>
  <% end %>
<% end %>

<% if @project.safe_attribute? 'inherit_members' %>
<p><%= f.check_box :inherit_members %></p>
<% end %>

<% if @project.safe_attribute?('default_version_id') && (default_version_options = project_default_version_options(@project)).present? %>
  <p><%= f.select :default_version_id, project_default_version_options(@project), :include_blank => true %></p>
<% end %>

<%= wikitoolbar_for 'project_description' %>

<% @project.custom_field_values.each do |value| %>
  <p><%= custom_field_tag_with_label :project, value %></p>
<% end %>
<%= call_hook(:view_projects_form, :project => @project, :form => f) %>
</div>

<% if @project.new_record? %>
<fieldset class="box tabular"><legend><%= l(:label_module_plural) %></legend>
<% Redmine::AccessControl.available_project_modules.each do |m| %>
    <label class="floating">
    <%= check_box_tag 'project[enabled_module_names][]', m, @project.module_enabled?(m), :id => "project_enabled_module_names_#{m}" %>
    <%= l_or_humanize(m, :prefix => "project_module_") %>
    </label>
<% end %>
<%= hidden_field_tag 'project[enabled_module_names][]', '' %>
</fieldset>
<% end %>

<% if @project.new_record? || @project.module_enabled?('issue_tracking') %>
<% unless @trackers.empty? %>
<fieldset class="box tabular" id="project_trackers"><legend><%=l(:label_tracker_plural)%></legend>
<% @trackers.each do |tracker| %>
    <label class="floating">
    <%= check_box_tag 'project[tracker_ids][]', tracker.id, @project.trackers.to_a.include?(tracker), :id => nil %>
    <%= tracker %>
    </label>
<% end %>
<%= hidden_field_tag 'project[tracker_ids][]', '' %>
</fieldset>
<% end %>

<% unless @issue_custom_fields.empty? %>
<fieldset class="box tabular" id="project_issue_custom_fields"><legend><%=l(:label_custom_field_plural)%></legend>
<% @issue_custom_fields.each do |custom_field| %>
    <label class="floating">
  <%= check_box_tag 'project[issue_custom_field_ids][]', custom_field.id, (@project.all_issue_custom_fields.include? custom_field),
        :disabled => (custom_field.is_for_all? ? "disabled" : nil),
        :id => nil %>
  <%= custom_field_name_tag(custom_field) %>
  </label>
<% end %>
<%= hidden_field_tag 'project[issue_custom_field_ids][]', '' %>
</fieldset>
<% end %>
<% end %>
<!--[eoform:project]-->

<% unless @project.identifier_frozen? %>
  <% content_for :header_tags do %>
    <%= javascript_include_tag 'project_identifier' %>
  <% end %>
<% end %>

<% if !User.current.admin? && @project.inherit_members? && @project.parent && User.current.member_of?(@project.parent) %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      $("#project_inherit_members").change(function(){
        if (!$(this).is(':checked')) {
          if (!confirm("<%= escape_javascript(l(:text_own_membership_delete_confirmation)) %>")) {
            $("#project_inherit_members").attr("checked", true);
          }
        }
      });
    });
  <% end %>
<% end %>

<%= javascript_tag do %>
$(document).ready(function() {
  $('#project_enabled_module_names_issue_tracking').on('change', function(){
    if ($(this).prop('checked')){
      $('#project_trackers, #project_issue_custom_fields').show();
    } else {
      $('#project_trackers, #project_issue_custom_fields').hide();
    }
  }).trigger('change');
});
<% end %>

app/views/projects/_sidebar.html.erb
<% if User.current.allowed_to?(:view_time_entries, @project) %>
  <h3><%= l(:label_spent_time) %></h3>
  <% if @total_hours.present? %>
    <p><span class="icon icon-time"><%= l_hours(@total_hours) %></span></p>
  <% end %>
  <p>
  <% if User.current.allowed_to?(:log_time, @project) %>
    <%= link_to l(:button_log_time), new_project_time_entry_path(@project) %> |
  <% end %>
  <%= link_to(l(:label_details), project_time_entries_path(@project)) %> |
  <%= link_to(l(:label_report), report_project_time_entries_path(@project)) %>
  </p>
<% end %>
<%= call_hook(:view_projects_show_sidebar_bottom, :project => @project) %>

app/views/projects/membershiprequest.html.haml
!= "$('#want-to-help').html('We have received your request and will review it soon!')"

app/views/projects/show.html.erb
<div class="contextual">
  <% if User.current.allowed_to?(:add_subprojects, @project) %>
    <%= link_to l(:label_subproject_new), new_project_path(:parent_id => @project), :class => 'icon icon-add' %>
  <% end %>
  <% if User.current.allowed_to?(:close_project, @project) %>
    <% if @project.active? %>
      <%= link_to l(:button_close), close_project_path(@project), :data => {:confirm => l(:text_are_you_sure)}, :method => :post, :class => 'icon icon-lock' %>
    <% else %>
      <%= link_to l(:button_reopen), reopen_project_path(@project), :data => {:confirm => l(:text_are_you_sure)}, :method => :post, :class => 'icon icon-unlock' %>
    <% end %>
  <% end %>
</div>

<% if ! @subprojects.any? %><h2><%=l(:label_overview)%></h2><% end %>
<% if ! @project.is_public? %>
  <p><b>Your project is still hidden!</b><br />Please unhide it by checking Settings->Information->Public.</p>
<% end %>
<% if @subprojects.any? %>
  <%= textilizable @project.description %>
<% end %>
<% unless @project.active? %>
  <p class="warning"><span class="icon icon-lock"><%= l(:text_project_closed) %></span></p>
<% end %>

<div class="splitcontentleft">
  <% if @subprojects.empty? %>
    <% if @project.description.present? %>
      <div class="wiki">
        <%= textilizable @project.description %>
      </div>
    <% end %>
    <% unless @project.homepage.blank? %>
      <ul><li><span class="label"><%=l(:field_homepage)%>:</span> <%= link_to_if uri_with_safe_scheme?(@project.homepage), @project.homepage, @project.homepage %></li></ul>
    <% end %>
  <% end %>

  <% if User.current.allowed_to?(:view_issues, @project) %>
  <div class="issues box">
    <h3><%=l(:label_issue_tracking)%></h3>
    <% if @trackers.present? %>
    <table class="list issue-report">
      <thead>
        <tr>
          <th></th>
          <th><%=l(:label_open_issues_plural)%></th>
          <th><%=l(:label_closed_issues_plural)%></th>
          <th><%=l(:label_total)%></th>
        </tr>
      </thead>
      <tbody>
      <% @trackers.each do |tracker| %>
        <tr class="<%= cycle("odd", "even") %>">
          <td class="name">
            <%= link_to tracker.name, project_issues_path(@project, :set_filter => 1, :tracker_id => tracker.id) %>
          </td>
          <td>
            <%= link_to @open_issues_by_tracker[tracker].to_i, project_issues_path(@project, :set_filter => 1, :tracker_id => tracker.id) %>
          </td>
          <td>
            <%= link_to (@total_issues_by_tracker[tracker].to_i - @open_issues_by_tracker[tracker].to_i), project_issues_path(@project, :set_filter => 1, :tracker_id => tracker.id, :status_id => 'c') %>
          </td>
          <td>
            <%= link_to @total_issues_by_tracker[tracker].to_i, project_issues_path(@project, :set_filter => 1, :tracker_id => tracker.id, :status_id => '*') %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <% end %>
    <p>
      <%= link_to l(:label_issue_view_all), project_issues_path(@project, :set_filter => 1) %>
      <% if User.current.allowed_to?(:view_calendar, @project, :global => true) %>
        | <%= link_to l(:label_calendar), project_calendar_path(@project) %>
      <% end %>
      <% if User.current.allowed_to?(:view_gantt, @project, :global => true) %>
        | <%= link_to l(:label_gantt), project_gantt_path(@project) %>
      <% end %>
    </p>
  </div>
  <% end %>
  <%= call_hook(:view_projects_show_left, :project => @project) %>
  <!-- activities -->
  <% if @events_by_day && @events_by_day.any?  %><!-- && authorize_for('activity', 'index') DOES NOT WORK YET -->
    <div class="box project-activity-container">
        <h3 class="icon22 icon22-tracker">Recent activities</h3>
        <% @events_by_day.keys.sort {|x,y| y <=> x }.each do |day| %>
          <h4><%= day_name(day.cwday) %> <%= day.day %></h4>
          <dl>
            <% @events_by_day[day].sort {|x,y| y.event_datetime <=> x.event_datetime }.each do |e| -%>
            <dt class="<%= e.class.name.downcase %> <%= cycle('odd', 'even') %>">
              <%= link_to truncate(h(e.event_title), 100), e.event_url %>  <span class="author"><%= e.event_author if e.respond_to?(:event_author) %></span></dt>
              <% end -%>
          </dl>
        <% end -%>
    </div>
  <% end %>
</div>

<div class="splitcontentright project-listing">
  <!-- START MEMBER BOX; alternative, use  render :partial => 'members_box' -->
  <% if @users_by_role.any? %>
    <div class="box project-member-container">
      <h3 class="icon22 icon22-users"><%=l(:label_member_plural)%></h3>
      <% @users_by_role.keys.sort_by{|role|
        result = case role.name
                 when 'Leader'
                   1
                 when 'Co-Leader'
                   5
                 when 'Member'
                   10
                 when 'Inactive Member'
                   15
                 when 'Pending Member'
                   20
                 else
                   100
                 end
        result
      }.each do |role| %>
      <p class="role">
      <h4><%= role.name %></h4>
      <% @users_by_role[role].sort.each do |user| %>
        <div class="role-user">
          <%= link_to_user_with_image user, 1 %>
        </div>
      <% end %>
      <div class="clearer"></div>
      </p>
    <% end %>
    <% if User.current.logged? && !User.current.member_of?(@project) %>
      <b><a href="javascript:void(0);" id="joinProjectLink">Join Project</a></b>
      <div id="want-to-help" style="display:none">
        <%= form_for :membership, url: request_membership_path(@project.identifier),  remote: true do %>
          How do you want to help:<br /><textarea id="team-membership-request-comment" name="description" style="height:inherit; width:99.5%" rows="2"></textarea><br />
          <%= submit_tag 'Submit team membership request' %>
        <% end %>
      </div>
    <% end %>
  </div>
  <% end %>

  <% if @news.any? && authorize_for('news', 'index') %>
  <div class="news box">
    <h3><%=l(:label_news_latest)%></h3>
    <%= render :partial => 'news/news', :collection => @news %>
    <p><%= link_to l(:label_news_view_all), project_news_index_path(@project) %></p>
  </div>
  <% end %>


  <%= call_hook(:view_projects_show_right, :project => @project) %>
</div>

<% content_for :sidebar do %>
  <%= render :partial => 'projects/sidebar' %>
<% end %>

<% content_for :header_tags do %>
<%= auto_discovery_link_tag(:atom, {:controller => 'activities', :action => 'index', :id => @project, :format => 'atom', :key => User.current.rss_key}) %>
<% end %>

<% html_title(l(:label_overview)) -%>