config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do

  get '/auto_complete/projects', controller: 'start', action: 'auto_complete_for_project_name'

  get 'projects/membershiprequest/:id', controller: 'projects', action: 'membershiprequest', as: :requestmembership
  post 'projects/membershiprequest/:id', controller: 'projects', action: 'membershiprequest', as: :request_membership

  match 'roles/workflow/:id/:role_id/:tracker_id', :controller => 'roles', :action => 'workflow', via: :all

  match 'help/:ctrl/:page', :controller => 'help', action: 'index', via: :all

  get 'time_entries/report', :controller => 'time_entry_reports', :action => 'report'
  get 'projects/:project_id/time_entries/report.:format', :controller => 'time_entry_reports', :action => 'report'

  match 'services/projects', :controller => 'project_services', :action => 'index', via: :all
  match 'services/projects/:id', :controller => 'project_services', :action => 'show', via: :all, as: :project_service_show

  match 'services/users/active', :controller => 'user_services', :action => 'active', via: :all
  match 'projects/show/:id', to: redirect('projects/%{id}'), via: :all
  resources :projects do
    get 'wiki.:format', controller: 'wiki', action: 'show'
    put 'wiki_styles/:id.css', controller: 'wiki_styles', action: 'update'
    put 'wiki.css', controller: 'wiki_styles', action: 'update'

  end
end

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html lang="<%= current_language %>">
<head>
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<title><%= html_title %></title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta name="description" content="<%= Redmine::Info.app_name %>" />
<meta name="keywords" content="issue,bug,tracker" />
<%= csrf_meta_tag %>
<%= favicon %>
<%= stylesheet_link_tag 'jquery/jquery-ui-1.11.0', 'application', 'responsive', :media => 'all' %>
<%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
<%= stylesheet_link_tag 'auto_complete', :plugin => 'typo3_forge', :media => 'all' %>
<%= javascript_heads %>
<%= javascript_include_tag 'custom-scripts', :plugin => 'typo3_forge' %>
<%= heads_for_theme %>
<%= call_hook :view_layouts_base_html_head %>
<% heads_for_wiki_formatter %>

<style type="text/css">
<% if @project && @project.topbartextcolor? then %>
#header #right-area, #header #right-area h1, #header #right-area a {
  color:<%=@project.topbartextcolor%>;
}
<% end %>
</style>
<!--[if IE]>
    <style type="text/css">
      * html body{ width: expression( document.documentElement.clientWidth < 900 ? '900px' : '100%' ); }
      body {behavior: url(<%= stylesheet_path "csshover.htc" %>);}
    </style>
<![endif]-->
<!-- page specific tags -->
<%= yield :header_tags -%>
</head>
<body class="<%= body_css_classes %>">
<%= call_hook :view_layouts_base_body_top %>
<div id="wrapper">
<div id="wrapper2">
<div id="wrapper3">
<div id="top-menu">
    <div id="account">
        <%= render_menu :account_menu -%>
    </div>
    <%= content_tag('div', "#{l(:label_logged_as)} #{link_to_user(User.current, :format => :username)}".html_safe, :id => 'loggedas') if User.current.logged? %>
    <%= render_menu :top_menu if User.current.logged? || !Setting.login_required? -%>
</div>

<div id="header">
    <div id="header-left">
        <div id="header-menu">
            <%= render_header_menu(@project) %>
        </div>
    </div>

    <div id="right-area" <%= render_header_image @project %>>
        <div id="quick-search">
            <%= form_tag({:controller => 'search', :action => 'index', :id => @project}, :method => :get ) do %>
            <%= hidden_field_tag(controller.default_search_scope, 1, :id => nil) if controller.default_search_scope %>
            <%= link_to l(:label_search), {:controller => 'search', :action => 'index', :id => @project}, :accesskey => accesskey(:search), :style => render_header_textcolor(@project) %>:
            <%= text_field_tag 'q', @question, :size => 20, :class => 'small', :accesskey => accesskey(:quick_search) %>
            <% end %>
        </div>

        <h1><%= @project ? @project.name : Setting.app_title %></h1>
        <div id="quicklinks"><%= (@project ? textilizable(@project.quicklinks) : '') %></div>
    </div>

    <div id="main-menu">
        <%= text_field_tag :projectname, '',  { id: "projectname_autocomplete", :class => 'projectsearch autocomplete_field', :placeholder => 'Project title search', data: {url: auto_complete_projects_path}} %>
        <div id="projectname_autocomplete_auto_complete" class="auto_complete" style="position: absolute; left: 5px; top: 24px; width: 215px; display: none;"></div>
        <%= render_main_menu(@project) %>
        <script>
          auto_complete('#projectname_autocomplete')
        </script>
    </div>
</div>

<div id="main" class="<%= sidebar_content? ? '' : 'nosidebar' %>">
  <div id="leftmenu">
      <%= render_left_menu (@project) %>
  </div>
    <div id="sidebar">
        <%= yield :sidebar %>
        <%= view_layouts_base_sidebar_hook_response %>
    </div>

    <div id="content">
        <%= render_flash_messages %>
        <%= yield %>
        <%= call_hook :view_layouts_base_content %>
        <div style="clear:both;"></div>
    </div>
</div>
</div>

<div id="ajax-indicator" style="display:none;"><span><%= l(:label_loading) %></span></div>
<div id="ajax-modal" style="display:none;"></div>

<div id="footer">
 Powered by <%= link_to Redmine::Info.app_name, Redmine::Info.url %> &copy; 2006-2019 Jean-Philippe Lang<br /><br />
</div>
</div>
<%= call_hook :view_layouts_base_body_bottom %>
<script type="text/javascript">
    var pkBaseURL = (("https:" == document.location.protocol) ? "https://piwik.typo3.org/" : "http://piwik.typo3.org/");
    document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
    try {
        var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 14);
        piwikTracker.trackPageView();
        piwikTracker.enableLinkTracking();
    } catch( err ) {}
</script>
<noscript><span style="visibility: hidden";><img src="http://piwik.typo3.org/piwik.php?idsite=14" style="border:0" alt=""/></span></noscript>
</body>
</html>